version: "3.9"

services:

  postgres:
    image: pgvector/pgvector:pg15
    container_name: ai-support-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gateway_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: ai-support-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: ai-support-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data

  gateway-service:
    build: ./gateway-service
    env_file:
      - ./gateway-service/.env
    ports:
      - "3000:3000"
    depends_on:
      - kafka
      - postgres

  intent-service:
    build: ./intent-service
    env_file:
      - ./intent-service/.env
    depends_on:
      - kafka
      - postgres

  retrieval-service:
    build: ./retrieval-service
    env_file:
      - ./retrieval-service/.env
    ports:
      - "4000:4000"
    depends_on:
      - kafka
      - postgres

  answer-service:
    build: ./answer-generation-service
    env_file:
      - ./answer-generation-service/.env
    depends_on:
      - kafka

volumes:
  postgres_data:
  kafka_data: